/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Game.Game;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.Image;

/**
 *
 * @author kirit
 */
public class MainMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());

    private JLabel lblBackground;

    public MainMenu() {
        initComponents();
        
        btnPlay.setFocusable(false);
        btnLoad.setFocusable(false);
        btnExit.setFocusable(false);
        Image icon = new ImageIcon(
                getClass().getResource("/resources/Icon/Main.png")
        ).getImage();

        setIconImage(icon);
        CreateBackground();
        SizeAdapted();
    }
    
    public void SizeAdapted() {
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screen.width, screen.height);
        setLocationRelativeTo(null);
        java.awt.EventQueue.invokeLater(() -> {
            SetImageLabel(lblPAquilix, "/resources/Gifs/Aquilix.gif");
            SetImageLabel(lblPMoon, "/resources/Gifs/Moon.gif");
            SetImageLabel(lblGalaxi, "/resources/Gifs/Galaxy.gif");
            SetImageLabel(lblPGas, "/resources/Gifs/Gas2.gif");
            SetImageLabel(lblPurpleHole, "/resources/Gifs/Hole.gif");
            
        });
    }

    public void CreateBackground() {

        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int width = screen.width;
        int height = screen.height;
        ImageIcon icon = new ImageIcon(
            getClass().getResource("/resources/Gifs/stars-space.gif")
        );
        Image img = icon.getImage();
        Image scaled = img.getScaledInstance(
            width,
            height,
            Image.SCALE_DEFAULT
        );
        lblBackground = new JLabel();
        lblBackground.setIcon(new ImageIcon(scaled));

        lblBackground.setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setBounds(0, 0, width, height);

        jPanel2.setOpaque(false);
        jPanel2.setBounds(0, 0, width, height);

        
        lblBackground.add(jPanel1);
        lblBackground.add(jPanel2);

        setContentPane(lblBackground);

        repaint();
        revalidate();
    }
    public void SetImageLabel(JLabel label, String ruta){

        ImageIcon icon = new ImageIcon(getClass().getResource(ruta));
        int labelWidth = label.getWidth();
        int labelHeight = label.getHeight();

        int iconWidth = icon.getIconWidth();
        int iconHeight = icon.getIconHeight();
        double scaleX = (double) labelWidth / iconWidth;
        double scaleY = (double) labelHeight / iconHeight;
        double scale = Math.min(scaleX, scaleY);
        int newWidth = (int)(iconWidth * scale);
        int newHeight = (int)(iconHeight * scale);
        Image image = icon.getImage().getScaledInstance(
                newWidth,
                newHeight,
                Image.SCALE_DEFAULT
        );
        label.setIcon(new ImageIcon(image));
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        lblPAquilix = new javax.swing.JLabel();
        lblGalaxi = new javax.swing.JLabel();
        lblPGas = new javax.swing.JLabel();
        lblPMoon = new javax.swing.JLabel();
        lblPurpleHole = new javax.swing.JLabel();
        lblPIces = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        lblGenesisBox = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GenesisBox 1.0.0");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPAquilix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Gifs/Aqualix.gif"))); // NOI18N
        jPanel2.add(lblPAquilix, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 260, 250));

        lblGalaxi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Gifs/Galaxy.gif"))); // NOI18N
        jPanel2.add(lblGalaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 630, 550, 120));

        lblPGas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Gifs/Gas3.gif"))); // NOI18N
        jPanel2.add(lblPGas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, -70, 530, 390));

        lblPMoon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Gifs/MMoon.gif"))); // NOI18N
        jPanel2.add(lblPMoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 880, 160, 110));

        lblPurpleHole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Gifs/Hole.gif"))); // NOI18N
        jPanel2.add(lblPurpleHole, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 350, 300));

        lblPIces.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Gifs/ices.gif"))); // NOI18N
        jPanel2.add(lblPIces, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 870, 100, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnPlay.setBackground(new java.awt.Color(10, 34, 63));
        btnPlay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(153, 153, 255));
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icon/New_Game.png"))); // NOI18N
        btnPlay.setText("New Game");
        btnPlay.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 1, 59)));
        btnPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 548, 0, 0);
        jPanel1.add(btnPlay, gridBagConstraints);

        lblGenesisBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Gifs/Logo Genesisbox.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = -313;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 247, 0, 208);
        jPanel1.add(lblGenesisBox, gridBagConstraints);

        btnLoad.setBackground(new java.awt.Color(10, 34, 63));
        btnLoad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoad.setForeground(new java.awt.Color(153, 153, 255));
        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icon/load.png"))); // NOI18N
        btnLoad.setText("Load");
        btnLoad.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 1, 59)));
        btnLoad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 548, 0, 0);
        jPanel1.add(btnLoad, gridBagConstraints);

        btnExit.setBackground(new java.awt.Color(10, 34, 63));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(153, 153, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icon/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 1, 59)));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 548, 53, 0);
        jPanel1.add(btnExit, gridBagConstraints);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        new Game();

        dispose();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
            Game game = new Game();
            game.loadGame();
            dispose();
        
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnPlay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGalaxi;
    private javax.swing.JLabel lblGenesisBox;
    private javax.swing.JLabel lblPAquilix;
    private javax.swing.JLabel lblPGas;
    private javax.swing.JLabel lblPIces;
    private javax.swing.JLabel lblPMoon;
    private javax.swing.JLabel lblPurpleHole;
    // End of variables declaration//GEN-END:variables
}